spring:
  application:
    name: service-health-monitor

  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/health_check?createDatabaseIfNotExist=true
    username: root
    password: root@39
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

monitor:
  scheduler-rate: 60000


